#ifndef RESOURCE_MAP_H_
#define RESOURCE_MAP_H_

#define PIN_XENSIV_BGT60TRXX_SPI_SCLK       CYBSP_RSPI_CLK
#define PIN_XENSIV_BGT60TRXX_SPI_MOSI       CYBSP_RSPI_MOSI
#define PIN_XENSIV_BGT60TRXX_SPI_MISO       CYBSP_RSPI_MISO
#define PIN_XENSIV_BGT60TRXX_SPI_CSN        CYBSP_RSPI_CS
#define PIN_XENSIV_BGT60TRXX_IRQ            CYBSP_RSPI_IRQ
#define PIN_XENSIV_BGT60TRXX_RSTN           CYBSP_RXRES_L

#endif  // RESOURCE_MAP_H_