#include "vitals_dsp.h"

#include <math.h>
#include <string.h>
#include <stddef.h>

/* CMSIS-DSP — available via COMPONENTS+=CMSIS_DSP in Makefile */
#include "arm_math.h"

/* -----------------------------------------------------------------------
 * Biquad filter coefficients — AUTO-GENERATED by tools/gen_biquad.py
 * Format: [b0, b1, b2, -a1, -a2] per stage (CMSIS DF2T convention)
 * Butterworth 4th-order bandpass, fs = 200 Hz
 * ----------------------------------------------------------------------- */
/* breath_bp — 0.1 to 0.5 Hz */
static const float32_t breath_bp_coeffs[20] = {
    /* stage 0 */ 1.5332455206e-09f,  3.0664910412e-09f, 1.5332455206e-09f,  1.9831552000e+00f, -9.8328482425e-01f,
    /* stage 1 */ 1.0000000000e+00f,  2.0000000000e+00f, 1.0000000000e+00f,  1.9918640138e+00f, -9.9209588971e-01f,
    /* stage 2 */ 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f,  1.9936380275e+00f, -9.9365659832e-01f,
    /* stage 3 */ 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f,  1.9983087710e+00f, -9.9831922276e-01f,
};
/* heart_bp — 0.9 to 2.0 Hz */
static const float32_t heart_bp_coeffs[20] = {
    /* stage 0 */ 8.5234009602e-08f,  1.7046801920e-07f, 8.5234009602e-08f,  1.9609894035e+00f, -9.6343124162e-01f,
    /* stage 1 */ 1.0000000000e+00f,  2.0000000000e+00f, 1.0000000000e+00f,  1.9724900795e+00f, -9.7374209449e-01f,
    /* stage 2 */ 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f,  1.9784925118e+00f, -9.8221208226e-01f,
    /* stage 3 */ 1.0000000000e+00f, -2.0000000000e+00f, 1.0000000000e+00f,  1.9907014721e+00f, -9.9153856817e-01f,
};
#define BP_STAGES 4

/* -----------------------------------------------------------------------
 * Blackman window: 2 * blackman(128) — pre-computed, matches pipeline.py
 * ----------------------------------------------------------------------- */
static const float32_t blackman128[128] = {
    -5.5511152e-17f,  7.0389001e-04f,  2.8136700e-03f,  6.3189400e-03f,
     1.1200000e-02f,  1.7400000e-02f,  2.4900000e-02f,  3.3600000e-02f,
     4.3600000e-02f,  5.4700000e-02f,  6.7000000e-02f,  8.0400000e-02f,
     9.4900000e-02f,  1.1060000e-01f,  1.2730000e-01f,  1.4510000e-01f,
     1.6390000e-01f,  1.8370000e-01f,  2.0450000e-01f,  2.2620000e-01f,
     2.4870000e-01f,  2.7200000e-01f,  2.9600000e-01f,  3.2060000e-01f,
     3.4580000e-01f,  3.7140000e-01f,  3.9740000e-01f,  4.2360000e-01f,
     4.5000000e-01f,  4.7650000e-01f,  5.0290000e-01f,  5.2920000e-01f,
     5.5530000e-01f,  5.8110000e-01f,  6.0640000e-01f,  6.3110000e-01f,
     6.5510000e-01f,  6.7830000e-01f,  7.0060000e-01f,  7.2190000e-01f,
     7.4200000e-01f,  7.6110000e-01f,  7.7880000e-01f,  7.9520000e-01f,
     8.1020000e-01f,  8.2370000e-01f,  8.3560000e-01f,  8.4590000e-01f,
     8.5460000e-01f,  8.6150000e-01f,  8.6680000e-01f,  8.7040000e-01f,
     8.7230000e-01f,  8.7250000e-01f,  8.7100000e-01f,  8.6780000e-01f,
     8.6310000e-01f,  8.5680000e-01f,  8.4900000e-01f,  8.3980000e-01f,
     8.2930000e-01f,  8.1760000e-01f,  8.0480000e-01f,  7.9090000e-01f,
     7.7610000e-01f,  7.6060000e-01f,  7.4440000e-01f,  7.2760000e-01f,
     7.1040000e-01f,  6.9290000e-01f,  6.7520000e-01f,  6.5730000e-01f,
     6.3940000e-01f,  6.2150000e-01f,  6.0380000e-01f,  5.8630000e-01f,
     5.6910000e-01f,  5.5230000e-01f,  5.3600000e-01f,  5.2020000e-01f,
     5.0500000e-01f,  4.9050000e-01f,  4.7670000e-01f,  4.6380000e-01f,
     4.5170000e-01f,  4.4050000e-01f,  4.3030000e-01f,  4.2110000e-01f,
     4.1290000e-01f,  4.0590000e-01f,  4.0000000e-01f,  3.9530000e-01f,
     3.9190000e-01f,  3.8980000e-01f,  3.8900000e-01f,  3.8980000e-01f,
     3.9190000e-01f,  3.9530000e-01f,  4.0000000e-01f,  4.0590000e-01f,
     4.1290000e-01f,  4.2110000e-01f,  4.3030000e-01f,  4.4050000e-01f,
     4.5170000e-01f,  4.6380000e-01f,  4.7670000e-01f,  4.9050000e-01f,
     5.0500000e-01f,  5.2020000e-01f,  5.3600000e-01f,  5.5230000e-01f,
     5.6910000e-01f,  5.8630000e-01f,  6.0380000e-01f,  6.2150000e-01f,
     6.3940000e-01f,  6.5730000e-01f,  6.7520000e-01f,  6.9290000e-01f,
     7.1040000e-01f,  7.2760000e-01f,  7.4440000e-01f,  7.6060000e-01f,
     7.7610000e-01f,  7.9090000e-01f,  8.0480000e-01f,  8.1760000e-01f,
};

/* -----------------------------------------------------------------------
 * Internal state
 * ----------------------------------------------------------------------- */
#define RING_ROWS   VITALS_WINDOW_CHIRPS
#define N           VITALS_SAMPLE_PER_CHIRP
#define WIN         VITALS_WINDOW_CHIRPS
#define STRIDE      VITALS_STRIDE

/* Ring buffer: [chirp_idx][sample_idx] stored flat */
static float32_t s_ring[RING_ROWS][N];
static int       s_n_chirp;   /* total chirps pushed (wraps at RING_ROWS) */
static int       s_write_idx; /* next write row */

/* FFT instance (size N = 128) */
static arm_rfft_fast_instance_f32 s_fft;

/* Biquad filter state (4 stages × 2 state vars = 8 floats each) */
static float32_t s_breath_state[BP_STAGES * 2];
static float32_t s_heart_state [BP_STAGES * 2];
static arm_biquad_cascade_df2T_instance_f32 s_breath_filt;
static arm_biquad_cascade_df2T_instance_f32 s_heart_filt;

/* Accumulated filtered output (window_size) */
static float32_t s_breath_buf[WIN];
static float32_t s_heart_buf [WIN];
static bool      s_filt_seeded;

/* Peak energy tracker for signal normalization */
static float32_t s_peak_energy;

/* -----------------------------------------------------------------------
 * Helpers
 * ----------------------------------------------------------------------- */

static void taubin_circle_fit(const float32_t *re, const float32_t *im,
                               int n, float32_t *cx_out, float32_t *cy_out,
                               float32_t *r_out)
{
    /* Port of pipeline.py _circle_fit_taubin */
    float32_t mx = 0.f, my = 0.f;
    for (int i = 0; i < n; i++) { mx += re[i]; my += im[i]; }
    mx /= n; my /= n;

    float32_t zmean = 0.f;
    float32_t u[WIN], v[WIN], z[WIN];
    for (int i = 0; i < n; i++) {
        u[i] = re[i] - mx; v[i] = im[i] - my;
        z[i] = u[i]*u[i] + v[i]*v[i];
        zmean += z[i];
    }
    zmean /= n;

    float32_t sqrt_zmean = sqrtf(zmean);
    float32_t z0[WIN];
    for (int i = 0; i < n; i++) z0[i] = (z[i] - zmean) / (2.f * sqrt_zmean);

    /* Build M^T M (3x3 normal equations for SVD-lite via power iteration) */
    /* M columns: z0, u, v  — solve for least-norm eigenvector of M^T M */
    float32_t mzz=0,mzu=0,mzv=0,muu=0,muv=0,mvv=0;
    for (int i = 0; i < n; i++) {
        mzz += z0[i]*z0[i]; mzu += z0[i]*u[i]; mzv += z0[i]*v[i];
        muu += u[i]*u[i];   muv += u[i]*v[i];  mvv += v[i]*v[i];
    }
    /* We want the smallest singular vector.  For a 3-element problem
       use the analytic smallest eigenvector of the symmetric 3x3 via
       inverse power iteration (3 iterations is plenty for float32). */
    float32_t a[3] = {1.f, 0.f, 0.f}; /* initial guess */
    for (int iter = 0; iter < 6; iter++) {
        /* b = (M^T M) * a — then we'll deflate the dominant component */
        float32_t b0 = mzz*a[0] + mzu*a[1] + mzv*a[2];
        float32_t b1 = mzu*a[0] + muu*a[1] + muv*a[2];
        float32_t b2 = mzv*a[0] + muv*a[1] + mvv*a[2];
        float32_t norm = sqrtf(b0*b0+b1*b1+b2*b2);
        if (norm < 1e-12f) break;
        a[0]=b0/norm; a[1]=b1/norm; a[2]=b2/norm;
    }
    /* Subtract dominant; repeat for smallest */
    /* Simpler: use QR-less smallest-eigenvec — just 3 power iters with shift */
    float32_t shift = mzz + muu + mvv; /* rough trace */
    float32_t sa[3] = {0.f, 1.f, 0.f};
    for (int iter = 0; iter < 8; iter++) {
        float32_t b0 = (mzz-shift)*sa[0] + mzu*sa[1] + mzv*sa[2];
        float32_t b1 = mzu*sa[0] + (muu-shift)*sa[1] + muv*sa[2];
        float32_t b2 = mzv*sa[0] + muv*sa[1] + (mvv-shift)*sa[2];
        float32_t norm = sqrtf(b0*b0+b1*b1+b2*b2);
        if (norm < 1e-12f) break;
        sa[0]=b0/norm; sa[1]=b1/norm; sa[2]=b2/norm;
    }

    float32_t a0 = sa[0] / (2.f * sqrt_zmean);
    float32_t a1 = sa[1], a2 = sa[2];
    float32_t a3 = -zmean * a0;

    if (fabsf(a0) < 1e-12f) { *cx_out=mx; *cy_out=my; *r_out=1.f; return; }

    *cx_out = -a1 / (2.f * a0) + mx;
    *cy_out = -a2 / (2.f * a0) + my;
    float32_t disc = (a1*a1 + a2*a2 - 4.f*a0*a3) / (4.f*a0*a0);
    *r_out   = (disc > 0.f) ? sqrtf(disc) : 1.f;
}

/* Count zero-crossing pairs in a bandpass signal → estimate frequency in BPM */
static float estimate_rate_bpm(const float32_t *sig, int n, float fs)
{
    int crossings = 0;
    for (int i = 1; i < n; i++) {
        if ((sig[i-1] < 0.f) != (sig[i] < 0.f)) crossings++;
    }
    /* Each breath/heartbeat produces two zero-crossings */
    float cycles = crossings / 2.f;
    float duration_s = (float)n / fs;
    return (cycles / duration_s) * 60.f;
}

/* -----------------------------------------------------------------------
 * Public API
 * ----------------------------------------------------------------------- */

void vitals_dsp_init(void)
{
    memset(s_ring, 0, sizeof(s_ring));
    s_n_chirp   = 0;
    s_write_idx = 0;
    s_peak_energy = 1.f;
    s_filt_seeded = false;

    arm_rfft_fast_init_f32(&s_fft, N);

    arm_biquad_cascade_df2T_init_f32(&s_breath_filt, BP_STAGES,
                                      breath_bp_coeffs, s_breath_state);
    arm_biquad_cascade_df2T_init_f32(&s_heart_filt, BP_STAGES,
                                      heart_bp_coeffs, s_heart_state);
    memset(s_breath_buf, 0, sizeof(s_breath_buf));
    memset(s_heart_buf,  0, sizeof(s_heart_buf));
}

bool vitals_dsp_push(const uint16_t *samples, VitalsResult *out)
{
    /* 1. Convert uint16 → float32 and store in ring */
    for (int i = 0; i < N; i++) {
        s_ring[s_write_idx][i] = (float32_t)samples[i];
    }
    s_write_idx = (s_write_idx + 1) % RING_ROWS;
    s_n_chirp++;

    if (s_n_chirp < WIN || (s_n_chirp % STRIDE) != 0) return false;

    /* 2. Gather window of chirps into local work buffer (newest WIN rows) */
    /* We'll work directly from the ring — compute the start row */
    int start_row = (s_write_idx - WIN + RING_ROWS) % RING_ROWS;

    /* 3. Compute range FFT for each chirp in window */
    /* Accumulate magnitude spectrum for target-bin selection */
    static float32_t fft_in[N], fft_out[N + 2];
    static float32_t mag_accum[N / 2];
    memset(mag_accum, 0, sizeof(mag_accum));

    /* IQ complex output: re[chirp][bin], im[chirp][bin] — store STRIDE newest */
    static float32_t iq_re[WIN], iq_im[WIN]; /* we only need the target bin */

    /* First pass: compute mean per chirp for DC removal, accumulate mag */
    for (int c = 0; c < WIN; c++) {
        int row = (start_row + c) % RING_ROWS;

        /* DC removal */
        float32_t mean = 0.f;
        for (int i = 0; i < N; i++) mean += s_ring[row][i];
        mean /= N;

        /* Apply IF scale + Blackman window */
        for (int i = 0; i < N; i++) {
            fft_in[i] = (s_ring[row][i] - mean) * VITALS_IF_SCALE * blackman128[i];
        }

        arm_rfft_fast_f32(&s_fft, fft_in, fft_out, 0);

        /* fft_out layout: [re0, re_N/2, re1, im1, re2, im2, ...] */
        for (int b = 0; b < N / 2; b++) {
            float32_t re = fft_out[2*b], im = fft_out[2*b+1];
            mag_accum[b] += sqrtf(re*re + im*im);
        }
    }

    /* 4. Target bin: argmax of accumulated magnitude for bins >= BIN_OFFSET */
    int target_bin = VITALS_BIN_OFFSET;
    float32_t max_mag = 0.f;
    float32_t total_energy = 0.f;
    for (int b = VITALS_BIN_OFFSET; b < N / 2; b++) {
        total_energy += mag_accum[b];
        if (mag_accum[b] > max_mag) { max_mag = mag_accum[b]; target_bin = b; }
    }

    /* Normalize signal strength */
    if (total_energy > s_peak_energy) s_peak_energy = total_energy;
    float32_t signal_norm = (s_peak_energy > 0.f) ? (total_energy / s_peak_energy) : 0.f;

    /* 5. Extract IQ at target bin for the full window */
    for (int c = 0; c < WIN; c++) {
        int row = (start_row + c) % RING_ROWS;

        float32_t mean = 0.f;
        for (int i = 0; i < N; i++) mean += s_ring[row][i];
        mean /= N;

        for (int i = 0; i < N; i++) {
            fft_in[i] = (s_ring[row][i] - mean) * VITALS_IF_SCALE * blackman128[i];
        }
        arm_rfft_fast_f32(&s_fft, fft_in, fft_out, 0);
        iq_re[c] = fft_out[2 * target_bin];
        iq_im[c] = fft_out[2 * target_bin + 1];
    }

    /* 6. Taubin circle fit → recenter + normalize */
    float32_t cx, cy, r;
    taubin_circle_fit(iq_re, iq_im, WIN, &cx, &cy, &r);
    if (r < 1e-6f) r = 1.f;

    /* 7. Phase extraction: incremental unwrap → displacement (rad_to_um) */
    const float rad_to_um = (3e8f / VITALS_F_CENTER_HZ) / (4.f * 3.14159265f) * 1e6f;
    static float32_t phase[WIN];
    phase[0] = 0.f;
    for (int c = 1; c < WIN; c++) {
        float32_t re_c = (iq_re[c] - cx) / r;
        float32_t im_c = (iq_im[c] - cy) / r;
        float32_t re_p = (iq_re[c-1] - cx) / r;
        float32_t im_p = (iq_im[c-1] - cy) / r;
        /* incremental phase: angle(iq[c] * conj(iq[c-1])) */
        float32_t dp_re = re_c*re_p + im_c*im_p;
        float32_t dp_im = im_c*re_p - re_c*im_p;
        phase[c] = phase[c-1] + atan2f(dp_im, dp_re);
    }

    /* displacement in µm, remove DC */
    float32_t disp[WIN];
    float32_t disp_mean = 0.f;
    for (int c = 0; c < WIN; c++) { disp[c] = phase[c] * rad_to_um; disp_mean += disp[c]; }
    disp_mean /= WIN;
    for (int c = 0; c < WIN; c++) disp[c] -= disp_mean;

    /* 8. Streaming bandpass filter: only feed the last STRIDE samples */
    float32_t *new_disp = &disp[WIN - STRIDE];

    if (!s_filt_seeded) {
        /* Seed filter initial state to avoid startup transient */
        for (int s = 0; s < BP_STAGES * 2; s++) {
            s_breath_state[s] = new_disp[0];
            s_heart_state[s]  = new_disp[0];
        }
        s_filt_seeded = true;
    }

    static float32_t breath_new[STRIDE], heart_new[STRIDE];
    arm_biquad_cascade_df2T_f32(&s_breath_filt, new_disp, breath_new, STRIDE);
    arm_biquad_cascade_df2T_f32(&s_heart_filt,  new_disp, heart_new,  STRIDE);

    /* Shift history left, append fresh stride */
    memmove(s_breath_buf, s_breath_buf + STRIDE, (WIN - STRIDE) * sizeof(float32_t));
    memmove(s_heart_buf,  s_heart_buf  + STRIDE, (WIN - STRIDE) * sizeof(float32_t));
    memcpy(s_breath_buf + WIN - STRIDE, breath_new, STRIDE * sizeof(float32_t));
    memcpy(s_heart_buf  + WIN - STRIDE, heart_new,  STRIDE * sizeof(float32_t));

    /* 9. Rate estimation via zero-crossing */
    float fs = 1.f / VITALS_PRT_S;
    float rr  = estimate_rate_bpm(s_breath_buf, WIN, fs);
    float bpm = estimate_rate_bpm(s_heart_buf,  WIN, fs);

    /* Clamp to physiologically plausible ranges */
    if (rr  < 4.f  || rr  > 40.f)  rr  = 0.f;
    if (bpm < 30.f || bpm > 200.f) bpm = 0.f;

    /* Presence: absolute peak magnitude per chirp > empirically validated 200k threshold */
#define PRESENCE_MAG_PER_CHIRP 100000.f
    out->bpm        = bpm;
    out->rr         = rr;
    out->signal     = signal_norm;
    out->target_bin = target_bin;
    out->present    = ((max_mag / WIN) >= PRESENCE_MAG_PER_CHIRP);

    return true;
}
